model:
  model_cls: VQVitModelPlus
  init_args:
    codebook_size: 16384
    codebook_embed_dim: 8
    codebook_l2_norm: True
    codebook_show_usage: True
    commit_loss_beta: 0.25
    entropy_loss_ratio: 0.0
    
    encoder_ch_mult: [1, 1, 2, 2, 4]
    decoder_ch_mult: [1, 1, 2, 2, 4]
    model_size: null
    encoder_size: "small"
    decoder_size: "small"
    num_latent_tokens: 256
    z_channels: 256
    dropout_p: 0.0

    # Encoder config
    multi_level_query_init: True

    # Decoder config 
    # (Deperecated)
    last_level_2d_query_init: False
    multi_level_2d_query_init:  False

    adaptive_gn: True
    d2s_up: True
    rot: True

    use_attn: False

    fea_rec_loss_type: "mse"
    fea_rec_loss_weight: 1.0

    distill_depth: 3
  
  # causal settings
  causal_settings:
    causal_type: null
    dynamic_length_train: False
    dynamic_level_range: null
    min_level: 0

trainer:
  global_batch_size: 128
  lr: 1e-4
  lr_scheduler: "cosine_v2"
  end_lr: 1e-5

  optimizer: "AdamW"
  global_seed: 0
  warmup: 0
  weight_decay: 1e-4
  beta1: 0.9
  beta2: 0.95
  max_grad_norm: 10.0

  distill_loss: True


loss:
  loss_cls: VQLoss
  params:
    disc_start: 0
    disc_weight: 0.5
    disc_type: "patchgan"
    disc_loss: "hinge"
    disc_dim: 64
    kw: 4
    norm: "batch"
    gen_adv_loss: "hinge"
    image_size: 256
    perceptual_weight: 1.0
    reconstruction_weight: 1.0
    reconstruction_loss: "l2"
    codebook_weight: 1.0
    aux_loss_end: 15000
    use_direct_rec_loss: False
    resnet_perceptual: False
    blur_ds: False
    lecam: False